### ISSUE TITLE
Logger not working with unit tests

### ISSUE THREAD

**Issue by morrigan** [NodeFactoryIo/hactar-backend#28]
Expected: Have info logs in tests

**Comment by MakMuftic** [comment]
@morrigan thanks to your idea and @nmlinaric testing, we fixed this issue by updating winston to the latest version, however, there is still one thing to discuss regarding e2e tests. We have 2 ways of enabling logger in e2e test:

**[1] enable it inside `before hook` for all e2e test (`index.test.ts`)**
:heavy_check_mark: only one line of code for setup
:x: generates additional logging output before all tests
:question: unable to control logging per test suit (_I am not sure if this is good or bad_)
**[2] enable it inside `before hook` for each test suit (`describe` block)**
:x: needs one line setup for each test suit
:heavy_check_mark: show only logger output from tests themself
:question: enables to control logging per test suit

**Comment by morrigan** [comment]
[1]
