### ISSUE TITLE
Disabling notifications

### ISSUE THREAD

**Issue by morrigan** [NodeFactoryIo/hactar-backend#48]
Save in database if user has enabled or disabled email notifications for node.

**Comment by morrigan** [comment]
@MakMuftic based on the current status of the task you are working, will this be a new table in db or can be used existing?

**Comment by MakMuftic** [comment]
@morrigan is this something that is controlled per `Node` or per `User`, maybe we discussed this but I am not sure on what we agreed at the end?

**Comment by morrigan** [comment]
> @morrigan is this something that is controlled per `Node` or per `User`, maybe we discussed this but I am not sure on what we agreed at the end?

Node. You can always check the design too :)
